/**
 * Development database helper using embedded PostgreSQL binaries.
 *
 * This is the default (and only) database runtime for this project.
 * Docker has been removed from the project — it was crashing on this
 * machine. This script provides a self-contained PostgreSQL instance
 * for local development and automated tests — with no external
 * service, Docker, or admin rights required.
 *
 * Usage:
 *   node scripts/dev-db.mjs start   [--port 5432]
 *   node scripts/dev-db.mjs stop
 *   node scripts/dev-db.mjs status
 *   node scripts/dev-db.mjs create-db facilityflow
 *   node scripts/dev-db.mjs reset
 */
import { execFileSync } from 'node:child_process';
import pg from 'pg';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const PORT = parsePort(process.argv);
const DATABASE_DIR = path.join(projectRoot, '.pgdata');
const LOG_FILE = path.join(DATABASE_DIR, 'server.log');
const BIN_DIR = path.join(
  projectRoot,
  'node_modules',
  '@embedded-postgres',
  'windows-x64',
  'native',
  'bin'
);
const INITDB = path.join(BIN_DIR, 'initdb.exe');
const PG_CTL = path.join(BIN_DIR, 'pg_ctl.exe');

function parsePort(argv) {
  const idx = argv.indexOf('--port');
  if (idx !== -1 && argv[idx + 1]) return Number(argv[idx + 1]);
  return Number(process.env.PG_PORT || 5432);
}

function run(bin, args) {
  return execFileSync(bin, args, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] });
}

function ensureTrustAuth() {
  // Local development only. Use trust + listen on localhost only.
  const hostFile = path.join(DATABASE_DIR, 'pg_hba.conf');
  fs.writeFileSync(
    hostFile,
    [
      '# Local development configuration (generated by dev-db.mjs)',
      'local   all   all                     trust',
      'host    all   all   127.0.0.1/32      trust',
      'host    all   all   ::1/128           trust',
    ].join('\n') + '\n'
  );
  fs.writeFileSync(
    path.join(DATABASE_DIR, 'postgresql.conf'),
    fs.readFileSync(path.join(DATABASE_DIR, 'postgresql.conf'), 'utf-8').replace(
      /^\s*#?listen_addresses\s*=.*$/m,
      "listen_addresses = 'localhost'"
    )
  );
}

async function initIfNeeded() {
  const dataDirExists = fs.existsSync(path.join(DATABASE_DIR, 'PG_VERSION'));
  if (!dataDirExists) {
    console.log(`[dev-db] Initialising PostgreSQL data directory at ${DATABASE_DIR}`);
    fs.mkdirSync(DATABASE_DIR, { recursive: true });
    try {
      run(INITDB, ['-D', DATABASE_DIR, '-U', 'postgres', '--auth=trust', '--encoding=UTF8', '--no-locale']);
    } catch (err) {
      // If initdb failed partway, retry on a clean dir.
      fs.rmSync(DATABASE_DIR, { recursive: true, force: true });
      fs.mkdirSync(DATABASE_DIR, { recursive: true });
      run(INITDB, ['-D', DATABASE_DIR, '-U', 'postgres', '--auth=trust', '--encoding=UTF8', '--no-locale']);
    }
    ensureTrustAuth();
    console.log('[dev-db] Initialised.');
  } else {
    ensureTrustAuth();
  }
}

async function start() {
  await initIfNeeded();
  if (await isRunning()) {
    console.log(`[dev-db] PostgreSQL already running on port ${PORT}.`);
    return;
  }
  try {
    run(PG_CTL, ['-D', DATABASE_DIR, '-l', LOG_FILE, '-o', `-p ${PORT}`, '-w', 'start']);
    console.log(`[dev-db] PostgreSQL started on port ${PORT}.`);
  } catch (err) {
    console.error('[dev-db] start failed:', err?.message || err);
    process.exitCode = 1;
  }
}

async function stop() {
  try {
    run(PG_CTL, ['-D', DATABASE_DIR, '-m', 'fast', '-w', 'stop']);
    console.log('[dev-db] PostgreSQL stopped.');
  } catch (err) {
    console.log(`[dev-db] stop finished (${err?.message || err}).`);
  }
}

async function isRunning() {
  const client = new pg.Client({ host: 'localhost', port: PORT, user: 'postgres' });
  try {
    await client.connect();
    await client.end();
    return true;
  } catch {
    return false;
  }
}

async function status() {
  if (await isRunning()) {
    const client = new pg.Client({ host: 'localhost', port: PORT, user: 'postgres' });
    await client.connect();
    const res = await client.query('SELECT version() AS v');
    console.log(`[dev-db] PostgreSQL is ready on port ${PORT}.`);
    console.log(res.rows[0].v.split(' on ')[0]);
    await client.end();
  } else {
    console.log(`[dev-db] PostgreSQL is NOT running on port ${PORT}.`);
  }
}

async function query(sql) {
  const client = new pg.Client({ host: 'localhost', port: PORT, user: 'postgres' });
  await client.connect();
  const res = await client.query(sql);
  await client.end();
  return res;
}

async function createDb(name) {
  try {
    const exists = await query(`SELECT 1 FROM pg_database WHERE datname='${name}'`);
    if (exists.rowCount === 0) {
      const client = new pg.Client({ host: 'localhost', port: PORT, user: 'postgres' });
      await client.connect();
      await client.query(`CREATE DATABASE "${name}"`);
      await client.end();
      console.log(`[dev-db] Database "${name}" created.`);
    } else {
      console.log(`[dev-db] Database "${name}" already exists.`);
    }
  } catch (err) {
    console.error('[dev-db] create-db failed:', err?.message || err);
    process.exitCode = 1;
  }
}

async function reset() {
  await stop();
  fs.rmSync(DATABASE_DIR, { recursive: true, force: true });
  console.log('[dev-db] Data directory removed.');
}

const command = process.argv[2];
switch (command) {
  case 'start':
    await start();
    break;
  case 'stop':
    await stop();
    break;
  case 'status':
    await status();
    break;
  case 'create-db':
    await createDb(process.argv[3] || 'facilityflow');
    break;
  case 'reset':
    await reset();
    break;
  default:
    console.log('Usage: node scripts/dev-db.mjs <start|stop|status|create-db|reset> [--port 5432]');
}